tasks:
  setupAwsCli:
    name: Install and Login to AWS CLI
    description: Installs AWS CLI and configures credentials
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/aws_cli_install.sh
      
  configureGit:
    name: Configure Git User Settings
    description: Set GitHub user email and name
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/git_settings_configure.sh
  
  installPythonPackages:
    name: Install Python Packages
    description: Installs development and AWS-related Python packages
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/python_sdk_install.sh

  installPowerShell:
    name: Install PowerShell
    description: Installs PowerShell and AWS Tools for PowerShell
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/powershell_cli_install.sh

  installTerraform:
    name: Install Terraform
    description: Installs Terraform CLI
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/terraform_cli_install.sh