tasks:
  setupAwsCli:
    name: Install and Login to AWS CLI
    description: Installs AWS CLI and configures credentials
    triggeredBy:
      - postDevcontainerStart
    command: |
      echo "Starting AWS CLI installation and login process..."

      AWS_CLI_ZIP="awsliv2.zip"
      AWS_INSTALLER_DIR="aws"
      AWS_V2_INSTALL_PATH="/usr/local/aws-cli/v2/current"
      TMPDIR=${TMPDIR:-/tmp}

      echo "Step 1: Creating temporary installation directory..."
      mkdir -p "$TMPDIR/awscli_install"
      cd "$TMPDIR/awscli_install" || { echo "❌ Failed to cd into temp directory"; exit 1; }

      echo "Step 2: Downloading AWS CLI zip package..."
      sudo curl -s -f "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "$AWS_CLI_ZIP" || { echo "❌ Failed to download AWS CLI"; exit 1; }

      echo "Step 3: Unzipping AWS CLI installer..."
      sudo unzip -o -q "$AWS_CLI_ZIP" || { echo "❌ Failed to unzip AWS CLI installer"; exit 1; }

      echo "Step 4: Running AWS CLI installer with update (retry on failure)..."
      sudo "./$AWS_INSTALLER_DIR/install" --update

      echo "Step 5: Cleaning up installation files..."
      sudo rm -rf "$AWS_CLI_ZIP" "$AWS_INSTALLER_DIR"

      echo "Step 6: Verifying AWS CLI installation..."
      if ! command -v aws &> /dev/null; then
        echo "AWS CLI could not be found. Please install it first."
        exit 1
      fi

      echo "Step 7: Configuring AWS CLI credentials..."
      aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
      aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
      aws configure set default.region "$AWS_DEFAULT_REGION"

      echo "AWS CLI setup and login process completed successfully."
      
  configureGit:
    name: Configure Git User Settings
    description: Set GitHub user email and name
    triggeredBy:
      - postDevcontainerStart
    command: |
      echo "Step 1: Verifying Git installation..."
      if ! command -v git &> /dev/null; then
        sudo apt-get update && sudo apt-get install -y git || { echo "Failed to install Git"; exit 1; }
      fi

      echo "Step 2: Setting Git user email..."
      if [ -z "$GIT_USER_EMAIL" ]; then
        echo "Failed: GIT_USER_EMAIL environment variable not set"
        exit 1
      fi
      git config --global user.email "$GIT_USER_EMAIL" || { echo "Failed to set Git email"; exit 1; }

      echo "Step 3: Setting Git user name..."
      if [ -z "$GIT_USER_NAME" ]; then
        echo "Failed: GIT_USER_NAME environment variable not set"
        exit 1
      fi
      git config --global user.name "$GIT_USER_NAME" || { echo "Failed to set Git name"; exit 1; }
  
  installPythonPackages:
    name: Install Python Packages
    description: Installs development and AWS-related Python packages
    command: |
      echo "Starting Python package installation..."

      echo "Step 1: Installing Black (code formatter)..."
      pip install black || { echo "Failed to install Black"; exit 1; }

      echo "Step 2: Installing boto3 with CRT support..."
      pip install 'boto3[crt]' || { echo "Failed to install boto3[crt]"; exit 1; }

      echo "Python packages installed successfully."